import { SITE_STATIC_DATA } from "@/constants"
import Link from "next/link"
import React, { useEffect } from "react"
import Logo from "@/static/images/logo.png"
import Head from "next/head"
import { Button, ThemeProvider, Typography } from "@mui/material"
import MuiTheme from "../../Theme/MuiTheme"
import SearchBox from "../SearchBox"


function Layout({ children }) {

    return (
        <ThemeProvider theme={MuiTheme}>

            <div>
                <div className="flex flex-col min-h-screen">
                    <Head>
                        <title>The best place to explore trade data
                        </title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
                        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
                        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;700;900&display=swap" rel="stylesheet"></link>
                    </Head>


                    {/* Header Goes Here */}

                    <header className="header">
                        <div className="max-w-screen-xl mx-auto p-3">
                            <div className="flex flex-wrap justify-between self-center">
                                <div className="flex">
                                    <div className="flex-initial text-center mr-2">

                                        <img
                                            style={{
                                                height: 32,
                                            }}
                                            src={Logo}
                                            alt="Tito Logo"
                                        />


                                    </div>
                                </div>
                                <div>
                                    <SearchBox />
                                </div>

                                <div className="flex items-center">
                                    <div className="flex ">

                                        {SITE_STATIC_DATA.primaryMenu.map((menu, index) => (
                                            <div className="mx-3 flex items-center cursor-pointer" >
                                                <h6 className="font-sm text-gray-400 ">
                                                    {menu.title}
                                                </h6>
                                            </div>
                                            // <Link
                                            //     to={menu.path}
                                            //     key={index}
                                            //     aria-label={menu.title}
                                            //     className={" text-xs font-bold px-4 rounded"}
                                            // >
                                            //     {menu.title}
                                            // </Link>
                                        ))}

                                    </div>
                                    <div className="ml-12">
                                        <Button variant="contained" style={{ background: 'black', textTransform: 'none' }}>Sign Up</Button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </header>


                    {/* Pages Goes Here */}

                    <main className={"flex-grow"}>{children}</main>


                    {/* Footer Goes Here */}

                    <footer>
                        <div className="bg-gray-800 text-white p-4">
                            {/* Top Footer */}
                            <div className="max-w-screen-xl mx-auto ">
                                <div className="flex flex-wrap self-center justify-between	">
                                    <div className="flex flex-wrap">
                                        <div className="flex-initial text-center mr-2 sm: pl-0 pb-2">
                                            <div className="flex flex-col">
                                                <div className="flex">

                                                    <img
                                                        style={{
                                                            height: 36,
                                                        }}
                                                        src={Logo}
                                                        alt="Tito Logo"
                                                    />

                                                </div>
                                                <div className="flex">
                                                    <div
                                                        style={{ fontSize: 12 }}
                                                        className="text-xs text-gray-400 self-center text-center"
                                                    >
                                                        Tito Software Inc,  © 2023
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div className="flex flex-wrap self-center">
                                        <div className="text-xs text-white mr-3">

                                            Contact Us

                                        </div>

                                        {/* Support */}
                                        <div className="text-xs text-white mr-3">

                                            Support

                                        </div>

                                        <div className="text-xs text-white mr-3">

                                            Terms

                                        </div>

                                        <div className="text-xs text-white mr-3">

                                            Privacy

                                        </div>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </footer>

                </div >
            </div >
        </ThemeProvider>
    )
}
export default Layout
